### ISSUE TITLE
Failed to build with erlang-23.0 version 

### ISSUE THREAD

**Issue by keerthanakalyan** [systemd/erlang-sd_notify#31] opened 2020-07-03 11:10 UTC
erlang-sd_notify failed to build with erlang version 23.0 with this error:

`ERROR: sh(cc c_src/sd_notify.o  -lsystemd -shared  -L"/usr/lib/erlang/lib/erl_interface-4.0/lib" -lerl_interface -lei -o priv/sd_notify_drv.so)
failed with return code 1 and the following output:
/bin/ld: cannot find -lerl_interface`

It seems that from version 23.0 of erlang, erl_interface is deprecated and removed. Could you please help is there a way to fix this issue?

**Comment by lemenkov** [comment] 2020-07-03 15:23
I've just reproduced it. Hold on - I'll propose a fix soon.

**Comment by Gsantomaggio** [comment] 2020-07-07 09:46
@lemenkov are you working on it?

the problem is solved using rebar3:
```
RUN yum install -y https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/23/el/7/x86_64/erlang-23.0.2-1.el7.x86_64.rpm
RUN wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 /usr/local/bin/
```
I am still having problems with the build:
```
+ mkdir -p /home/sd/packaging/centos/BUILDROOT/erlang-sd_notify-1.0-1.el8.x86_64/usr/lib64/erlang/lib/sd_notify-1.0/ebin /home/sd/packaging/centos/BUILDROOT/erlang-sd_notify-1.0-1.el8.x86_64/usr/lib64/erlang/lib/sd_notify-1.0/priv
+ install -m 644 -p ebin/sd_notify.app /home/sd/packaging/centos/BUILDROOT/erlang-sd_notify-1.0-1.el8.x86_64/usr/lib64/erlang/lib/sd_notify-1.0/ebin
install: cannot stat 'ebin/sd_notify.app': No such file or directory
```

**Comment by Gsantomaggio** [comment] 2020-07-07 13:08
Ok I can compile using rebar3

```
 make compile
/usr/local/bin/rebar3 compile
===> Verifying dependencies...
===> Compiling sd_notify
make[1]: Entering directory '/home/sd/c_src'
make[1]: '/home/sd/c_src/../priv/sd_notify_drv.so' is up to date.
make[1]: Leaving directory '/home/sd/c_src'
```

**Comment by lemenkov** [comment] 2020-07-07 14:08
@Gsantomaggio try the current version - I've switched away from NIF + added more tests.

@keerthanakalyan should be fixed now (see #35).

**Comment by lemenkov** [comment] 2020-07-07 14:11
@Gsantomaggio could you please check that everything (including deb builds) still works on Debian?

**Comment by Gsantomaggio** [comment] 2020-07-07 14:18
@lemenkov  ok going to test

**Comment by Gsantomaggio** [comment] 2020-07-07 15:52
```bash
[vagrant@localhost ~]$ NOTIFY_SOCKET=/run/systemd/notify erl
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Eshell V11.0.2  (abort with ^G)
1> sd_notify:ready().
=INFO REPORT==== 7-Jul-2020::15:50:23.224349 ===
systemd: <<"READY=1">>
ok
2>
```

I'd say that it works, I had to change a couple of things.


__built using `rebar3`__

**Comment by lemenkov** [comment] 2020-07-07 20:44
Ok, good. Closing this then.

**Closed as completed by lemenkov** 2020-07-07 20:44 UTC
Labels: bug
